---
name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        compiler:
          - package: gcc-13
            bin: g++
            os: ubuntu-24.04
          - package: gcc-12
            bin: g++
            os: ubuntu-latest
          - package: gcc-11
            bin: g++
            os: ubuntu-latest
    runs-on: ${{ matrix.compiler.os }}
    steps:
      - name: checkout-scm
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: setup
        run: sudo apt install ${{ matrix.compiler.package }} make
      - name: test
        run: make test CXX=${{ matrix.compiler.bin }}
